#!/bin/bash

# 使用GitHub Token推送代码
# 需要你在GitHub上生成Personal Access Token

echo "🎬 AI导演工作室网站 - 代码推送指南"
echo "======================================"
echo ""
echo "由于需要GitHub认证，请按照以下步骤操作："
echo ""
echo "第1步：生成GitHub Personal Access Token"
echo "--------------------------------------"
echo "1. 访问 https://github.com/settings/tokens"
echo "2. 点击 'Generate new token'"
echo "3. 选择 'classic' token"
echo "4. 设置权限：至少需要 'repo' 权限"
echo "5. 生成Token并复制"
echo ""
echo "第2步：使用Token推送代码"
echo "-----------------------"
echo "在终端执行以下命令："
echo ""
echo "cd /root/.openclaw/workspace/website"
echo "git remote set-url origin https://你的GitHub用户名:你的Token@github.com/lovebitt/ai-director-studio.git"
echo "git push -u origin main"
echo ""
echo "第3步：Vercel部署"
echo "----------------"
echo "推送成功后，访问："
echo "https://vercel.com/new"
echo "导入仓库 'ai-director-studio'"
echo "点击 'Deploy'"
echo ""
echo "第4步：访问网站"
echo "--------------"
echo "部署完成后，访问："
echo "https://ai-director-studio.vercel.app"
echo ""
echo "======================================"
echo "🎬 代码已准备就绪，等待你的Token推送！"